CREATE DATABASE MULTICAPA

USE MULTICAPA

CREATE TABLE AGENDA(
ID INT IDENTITY (1,1) PRIMARY KEY NOT NULL,
NOMBRE NVARCHAR (50) NOT NULL,
APELLIDO NVARCHAR (50) NOT NULL,
GENERO VARCHAR (50),
ESTADO_CIVIL VARCHAR (50),
TELEFONO VARCHAR (50),
DIRRECCION VARCHAR (50),
CORREO VARCHAR (50)
)


INSERT INTO AGENDA VALUES('Lisbeth María','Morales Eusebio','Femenino','Soltero','8295260410','Villa Coral Casa 6','202010658@itla.edu.do')
INSERT INTO AGENDA VALUES('Carlos David','Morales Eusebio','Masculino','Soltero','8292481086','Villa Coral Casa 6','Ccastro240@gmail.com')

SELECT * FROM AGENDA

--PROCEDIMIENTO BUSQUEDA SP

CREATE PROCEDURE SP_BUSCARCONTACTO
@BUSCAR NVARCHAR(50) AS 
SELECT * FROM AGENDA WHERE NOMBRE LIKE @BUSCAR + '%'

---PROCEDIMIENTO INSERTAR

CREATE PROCEDURE SP_INSERTARCONTACTO
@NOMBRE NVARCHAR (50),
@APELLIDO NVARCHAR (50),
@GENERO VARCHAR (50),
@ESTADO_CIVIL VARCHAR (50),
@TELEFONO VARCHAR (50),
@DIRRECCION VARCHAR (50),
@CORREO VARCHAR (50)
AS
INSERT INTO AGENDA VALUES(@NOMBRE,@APELLIDO,@GENERO,@ESTADO_CIVIL,@TELEFONO,@DIRRECCION,@CORREO)

---PROCEDIMIENTO MODIFICAR

CREATE PROCEDURE SP_EDITARCONTACTO
@ID INT,
@NOMBRE NVARCHAR (50),
@APELLIDO NVARCHAR (50),
@GENERO VARCHAR (50),
@ESTADO_CIVIL VARCHAR (50),
@TELEFONO VARCHAR (50),
@DIRRECCION VARCHAR (50),
@CORREO VARCHAR (50)
AS
UPDATE AGENDA SET NOMBRE = @NOMBRE, APELLIDO = @APELLIDO, GENERO = @GENERO, ESTADO_CIVIL = @ESTADO_CIVIL,
TELEFONO = @TELEFONO, DIRRECCION = @DIRRECCION, CORREO = @CORREO WHERE ID = @ID
GO

---PROCEDIMIENTO ELIMINAR

CREATE PROCEDURE SP_ELIMINARCONTACTO
@ID INT
AS
DELETE AGENDA WHERE ID = @ID



